// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc5aQRx_QOYsQs12MsTV2beUfzqLbS4KU',
    appId: '1:596830035513:web:f27c27f1c46d395f9437e8',
    messagingSenderId: '596830035513',
    projectId: 'asher-app-intellispend',
    authDomain: 'asher-app-intellispend.firebaseapp.com',
    storageBucket: 'asher-app-intellispend.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOY_UWMzXJ525YPRXtn6nhe-YOIx2DtcA',
    appId: '1:596830035513:android:74c05e874bea98e99437e8',
    messagingSenderId: '596830035513',
    projectId: 'asher-app-intellispend',
    storageBucket: 'asher-app-intellispend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJcTtMeG7MyKp3OgMD9XVOvbkfCi5TI0s',
    appId: '1:596830035513:ios:a745289617906d769437e8',
    messagingSenderId: '596830035513',
    projectId: 'asher-app-intellispend',
    storageBucket: 'asher-app-intellispend.firebasestorage.app',
    iosClientId: '596830035513-s3qr5p9s78b78if284q1lkaj23t1al5k.apps.googleusercontent.com',
    iosBundleId: 'app.asher.intellispend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJcTtMeG7MyKp3OgMD9XVOvbkfCi5TI0s',
    appId: '1:596830035513:ios:a745289617906d769437e8',
    messagingSenderId: '596830035513',
    projectId: 'asher-app-intellispend',
    storageBucket: 'asher-app-intellispend.firebasestorage.app',
    iosClientId: '596830035513-s3qr5p9s78b78if284q1lkaj23t1al5k.apps.googleusercontent.com',
    iosBundleId: 'app.asher.intellispend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc5aQRx_QOYsQs12MsTV2beUfzqLbS4KU',
    appId: '1:596830035513:web:1bdabd1acd614b139437e8',
    messagingSenderId: '596830035513',
    projectId: 'asher-app-intellispend',
    authDomain: 'asher-app-intellispend.firebaseapp.com',
    storageBucket: 'asher-app-intellispend.firebasestorage.app',
  );
}
